development: &default
  adapter: postgresql
  host: localhost
  database: quick_fixx_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: quick_fixx_test

production:
  adapter: postgresql
  database: quick_fixx_production
  pool: 5
  timeout: 5000
